apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/qcloud-loadbalancer-clusterid: {{.Values.clusterid}}
    service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: {{.Values.subnetid}}
  labels:
    qcloud-app: flink-job-manager
  name: flink-ui
  namespace: {{.Values.namespace}}
spec:
  ports:
  - name: flink-job-manager-ui-port
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    qcloud-app: flink-job-manager
  sessionAffinity: None
  type: LoadBalancer